name: Build Cyber IO Push
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Android SDK tools
        run: echo "$ANDROID_HOME/build-tools/30.0.3" >> $GITHUB_PATH

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Get short commit hash
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Test CyberIO
        run: |
          chmod +x gradlew
          ./gradlew test

      - name: Build Cyber-IO
        run: |
          chmod +x gradlew
          ./gradlew :main:deploy

      - uses: actions/upload-artifact@v2
        with:
          name: CyberIO-Unzip-This
          path: main/build/tmp/deploy/*.jar

  release:
    needs: build
    if: |
      contains(github.event.head_commit.message,'[release]') &&
      github.repository == 'liplum/CyberIO'
    runs-on: ubuntu-latest
    env:
      GH_REPO: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: CyberIO
          path: out

      - name: Retrieve meta
        id: retrieveMeta
        run: |
          chmod +x gradlew
          ./gradlew retrieveMeta

      - name: Create release
        if: ${{ steps.retrieveMeta.outputs.tag_exist == 'false' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEADER: ${{ steps.retrieveMeta.outputs.header }}
          VERSION: ${{ steps.retrieveMeta.outputs.version }}
        run: |
          gh release create "$VERSION" --title "$HEADER" --notes-file "Info/ReleaseMessage/$VERSION.md" out/*

      - name: Update release file
        if: ${{ steps.retrieveMeta.outputs.tag_exist == 'true' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.retrieveMeta.outputs.version }}
        run: |
          gh release upload "$VERSION" out/* --clobber